Enumerable
Isabellanamutenda/Enumerable pull request #3
Opened 2021-11-23 19:14 UTC by Isabellanamutenda

2021-11-23 21:59 UTC, ArthurGC requested changes
# Required Changes ♻️ :warning: 
Hi  @Isabellanamutenda  @lily-coder 

Amazing job!
There are some issues that you still need to work on to go to the next project but you are almost there! 

![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Good Points :+1: :
You used proper GitHub Flow :heavy_check_mark:
Your linter checks are all passing :heavy_check_mark:
Your PR messages are descriptive :heavy_check_mark:
Your commit messages are meaningful :heavy_check_mark:

## Aspects to improve ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-23 21:59 UTC, ArthurGC commented on my_enumerable
> +end
- [ ] You might want to consider fixing this file because it doesn't have an extension. It should be `my_enumerable.rb` 😉

2021-11-23 21:59 UTC, ArthurGC commented on my_list.rb
> +
- [ ] It would be better to fix the `myenumerable` because the right name for your module file is `my_enumerable`. ♻️

2021-11-24 01:10 UTC, Isabellanamutenda commented on my_list.rb
> +
Fixed

2021-11-24 01:10 UTC, Isabellanamutenda commented on my_enumerable
> +end
Fixed

2021-11-24 02:27 UTC, eri8-9 approved these changes
Hi @Isabellanamutenda, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- I see that you did the work, well done!

![Felix](https://media.giphy.com/media/hlQeY3PbhH3i/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 19:29 UTC, merged